### PR TITLE
define setter methods for versioned columns

### PR DESCRIPTION
**Pull request by ksenia-zalesnaya**
I think along with get methods we need setters. It is useful, for example, for integration with Factory Girl.

### CODE REVIEW

**Comment by JosephHalter** [comment]
It's not the recommended usage, the best practice is to use something like https://github.com/JosephHalter/yeti for your editor and rely on `update_attributes` or `attributes=` rather than defining setter methods for each versioned column in master. However, since you need it, I'll add it as an option.

**Comment by ksenia-zalesnaya** [comment]
@JosephHalter I look at this model from principles of encapsulation and thought that versioned columns should not differ from not versioned. So why not use all available methods like setters and update, not just update_attributes and attributes=?

**Comment by JosephHalter** [comment]
From my experience, the master will contain columns too and it's better to not mix updating the master attributes from the version attributes, that's why update_attributes will only update the version attributes and master attributes have to be assigned manually. If you use it long enough you'll probably come to the same realization. Also, for the code it's better to avoid `send` and replace it with `public_send` when possible. New version of the gem is pending.

**Comment by JosephHalter** [comment]
Fixed by commit 277aed9

**Comment by JosephHalter** [comment]
Version 0.8.8 is release, just use like this:

```
plugin :bitemporal, version_class: VersionClass, writers: true
```

**Pull request closed without merging**
